//! Integration tests for --ask flag (interactive mode)
//!
//! This test suite verifies the integration of the --ask flag
//! with the CLI, pipeline, and user interaction flows.

use clap::Parser;
use ltmatrix::cli::args::Args;

#[cfg(test)]
mod cli_integration_tests {
    use super::*;

    /// Test that --ask flag is properly parsed by CLI
    #[test]
    fn test_ask_flag_parsing() {
        let args = Args::parse_from(["ltmatrix", "--ask", "add authentication"]);

        assert!(args.ask, "ask flag should be true");
        assert_eq!(args.goal, Some("add authentication".to_string()));
    }

    /// Test that --ask works with other flags
    #[test]
    fn test_ask_flag_with_other_options() {
        let args = Args::parse_from([
            "ltmatrix",
            "--ask",
            "--fast",
            "--output",
            "json",
            "build API",
        ]);

        assert!(args.ask, "ask flag should be true");
        assert!(args.fast, "fast flag should be true");
        assert_eq!(args.goal, Some("build API".to_string()));
    }

    /// Test that --ask flag defaults to false
    #[test]
    fn test_ask_flag_default() {
        let args = Args::parse_from(["ltmatrix", "test goal"]);

        assert!(!args.ask, "ask flag should default to false");
    }

    /// Test --ask with dry-run mode
    #[test]
    fn test_ask_flag_with_dry_run() {
        let args = Args::parse_from(["ltmatrix", "--ask", "--dry-run", "test goal"]);

        assert!(args.ask, "ask flag should be true");
        assert!(args.dry_run, "dry-run flag should be true");
    }

    /// Test --ask with config file
    #[test]
    fn test_ask_flag_with_config() {
        let args = Args::parse_from(["ltmatrix", "--ask", "--config", "custom.toml", "test goal"]);

        assert!(args.ask, "ask flag should be true");
        assert_eq!(args.config, Some(std::path::PathBuf::from("custom.toml")));
    }
}

#[cfg(test)]
mod clarification_flow_tests {
    use ltmatrix::interactive::clarify::{
        ClarificationQuestion, ClarificationSession, QuestionType,
    };

    /// Test clarification flow for ambiguous authentication goal
    #[test]
    fn test_ambiguous_auth_goal_generates_questions() {
        let goal = "add authentication to the app";
        // Questions would be generated by the implementation
        // For now, we verify the session can be created
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
        // Verify session can accept questions
        let question = ClarificationQuestion {
            id: "auth_method".to_string(),
            question_text: "Which authentication method?".to_string(),
            question_type: QuestionType::Choice,
            options: Some(vec!["JWT".to_string(), "OAuth".to_string()]),
            default_value: None,
            required: true,
            multi_select: false,
        };
        let mut session = session;
        session.add_question(question);
        assert_eq!(session.questions.len(), 1);
    }

    /// Test clarification flow for specific authentication goal
    #[test]
    fn test_specific_auth_goal_no_auth_question() {
        let goal = "add JWT authentication with OAuth2 support";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test clarification flow for API ambiguity
    #[test]
    fn test_ambiguous_api_goal_generates_questions() {
        let goal = "build an API for user management";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test clarification flow for database ambiguity
    #[test]
    fn test_database_goal_generates_questions() {
        let goal = "add database storage for user data";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test clarification flow for testing ambiguity
    #[test]
    fn test_testing_goal_generates_questions() {
        let goal = "add tests";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test that very short goals always generate clarification
    #[test]
    fn test_very_short_goal_requires_clarification() {
        let goal = "add tests";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test clarification session lifecycle
    #[test]
    fn test_clarification_session_lifecycle() {
        let mut session = ClarificationSession::new("add authentication");

        // Add questions
        session.add_question(ClarificationQuestion {
            id: "auth_method".to_string(),
            question_text: "Which authentication method?".to_string(),
            question_type: QuestionType::Choice,
            options: Some(vec!["JWT".to_string(), "OAuth".to_string()]),
            default_value: Some("JWT".to_string()),
            required: true,
            multi_select: false,
        });

        // Answer question
        session.answer_question("auth_method", "JWT").unwrap();

        // Verify answered
        assert!(session.all_required_answered());

        // Mark complete
        session.mark_completed();
        assert!(session.completed);
    }

    /// Test prompt injection for planning
    #[test]
    fn test_prompt_injection_for_planning() {
        let mut session = ClarificationSession::new("build API");

        session.add_question(ClarificationQuestion {
            id: "api_type".to_string(),
            question_text: "What type of API?".to_string(),
            question_type: QuestionType::Choice,
            options: Some(vec!["REST".to_string(), "GraphQL".to_string()]),
            default_value: None,
            required: true,
            multi_select: false,
        });

        session.answer_question("api_type", "REST").unwrap();

        let injection = session.generate_prompt_injection();

        assert!(injection.contains("User Clarifications"));
        assert!(injection.contains("What type of API?"));
        assert!(injection.contains("REST"));
        assert!(injection.contains("End Clarifications"));
    }
}

#[cfg(test)]
mod question_type_tests {
    use ltmatrix::interactive::clarify::{QuestionType, QuestionType::*};

    /// Test all question types are properly defined
    #[test]
    fn test_question_type_variants() {
        let types = vec![Text, Choice, Confirm, MultiSelect];

        for qtype in types {
            let display = format!("{}", qtype);
            assert!(!display.is_empty(), "Each type should have display text");
        }
    }

    /// Test text input question type
    #[test]
    fn test_text_question_type() {
        let qtype = QuestionType::Text;
        assert_eq!(format!("{}", qtype), "text input");
    }

    /// Test choice question type
    #[test]
    fn test_choice_question_type() {
        let qtype = QuestionType::Choice;
        assert_eq!(format!("{}", qtype), "multiple choice");
    }

    /// Test confirm question type
    #[test]
    fn test_confirm_question_type() {
        let qtype = QuestionType::Confirm;
        assert_eq!(format!("{}", qtype), "confirmation");
    }

    /// Test multi-select question type
    #[test]
    fn test_multiselect_question_type() {
        let qtype = QuestionType::MultiSelect;
        assert_eq!(format!("{}", qtype), "multi-select");
    }
}

#[cfg(test)]
mod session_validation_tests {
    use ltmatrix::interactive::clarify::{
        ClarificationQuestion, ClarificationSession, QuestionType,
    };

    /// Test that unanswered required questions are detected
    #[test]
    fn test_detect_unanswered_required_questions() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "q1".to_string(),
            question_text: "Q1".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        });

        session.add_question(ClarificationQuestion {
            id: "q2".to_string(),
            question_text: "Q2".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        });

        session.answer_question("q1", "answer").unwrap();

        let unanswered = session.unanswered_required();
        assert_eq!(unanswered.len(), 1);
        assert_eq!(unanswered[0].id, "q2");
    }

    /// Test skipping optional question with default
    #[test]
    fn test_skip_optional_with_default() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "optional".to_string(),
            question_text: "Optional?".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: Some("default_value".to_string()),
            required: false,
            multi_select: false,
        });

        session.skip_question("optional").unwrap();

        assert_eq!(
            session.answers.get("optional"),
            Some(&"default_value".to_string())
        );
    }

    /// Test that skipping required question fails
    #[test]
    fn test_cannot_skip_required_without_default() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "required".to_string(),
            question_text: "Required?".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        });

        let result = session.skip_question("required");
        assert!(result.is_err(), "Should not skip required question");
    }

    /// Test answering non-existent question fails
    #[test]
    fn test_answer_nonexistent_question_fails() {
        let mut session = ClarificationSession::new("test");

        let result = session.answer_question("nonexistent", "answer");
        assert!(result.is_err());
    }

    /// Test duplicate question replacement
    #[test]
    fn test_duplicate_question_replaces_existing() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "duplicate".to_string(),
            question_text: "First version".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        });

        session.add_question(ClarificationQuestion {
            id: "duplicate".to_string(),
            question_text: "Second version".to_string(),
            question_type: QuestionType::Choice,
            options: Some(vec!["A".to_string(), "B".to_string()]),
            default_value: None,
            required: true,
            multi_select: false,
        });

        assert_eq!(session.questions.len(), 1);
        assert_eq!(session.questions[0].question_text, "Second version");
        assert!(matches!(
            session.questions[0].question_type,
            QuestionType::Choice
        ));
    }
}

#[cfg(test)]
mod edge_case_tests {
    use ltmatrix::interactive::clarify::{
        ClarificationQuestion, ClarificationSession, QuestionType,
    };

    /// Test empty goal
    #[test]
    fn test_empty_goal_handling() {
        let session = ClarificationSession::new("");
        assert_eq!(session.goal, "");
    }

    /// Test goal with special characters
    #[test]
    fn test_special_characters_in_goal() {
        let goal = "Add feature: \"quoted\" and 'apostrophes' & symbols!";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test very long goal
    #[test]
    fn test_very_long_goal() {
        let goal = "a".repeat(10000);
        let session = ClarificationSession::new(&goal);
        assert_eq!(session.goal.len(), 10000);
    }

    /// Test session with no questions
    #[test]
    fn test_session_with_no_questions() {
        let session = ClarificationSession::new("clear goal");
        assert!(session.questions.is_empty());
        assert!(session.all_required_answered());
        assert!(session.unanswered_required().is_empty());
    }

    /// Test question with very long text
    #[test]
    fn test_very_long_question_text() {
        let long_text = "Question".repeat(1000);
        let question = ClarificationQuestion {
            id: "long_q".to_string(),
            question_text: long_text,
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        };

        assert_eq!(question.question_text.len(), 8000);
    }

    /// Test question with many options
    #[test]
    fn test_question_with_many_options() {
        let options: Vec<String> = (1..=100).map(|i| format!("Option {}", i)).collect();

        let question = ClarificationQuestion {
            id: "many_options".to_string(),
            question_text: "Choose one".to_string(),
            question_type: QuestionType::Choice,
            options: Some(options),
            default_value: None,
            required: true,
            multi_select: false,
        };

        assert_eq!(question.options.as_ref().unwrap().len(), 100);
    }

    /// Test answer with special characters
    #[test]
    fn test_answer_with_special_characters() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "q1".to_string(),
            question_text: "Question?".to_string(),
            question_type: QuestionType::Text,
            options: None,
            default_value: None,
            required: true,
            multi_select: false,
        });

        let special_answer =
            "Answer with 'quotes', \"double quotes\", & symbols, and\nnewlines\ttabs";
        session.answer_question("q1", special_answer).unwrap();

        assert_eq!(session.answers.get("q1"), Some(&special_answer.to_string()));
    }

    /// Test clear goal generates minimal questions
    #[test]
    fn test_clear_goal_generates_minimal_questions() {
        let goal =
            "Add unit tests for the UserService.login() method using mockito for HTTP mocking";
        let session = ClarificationSession::new(goal);
        assert_eq!(session.goal, goal);
    }

    /// Test prompt injection with no answers
    #[test]
    fn test_prompt_injection_with_no_answers() {
        let session = ClarificationSession::new("test");
        let injection = session.generate_prompt_injection();

        assert!(
            injection.is_empty(),
            "Should return empty string when no answers"
        );
    }

    /// Test multi-select answer format
    #[test]
    fn test_multiselect_answer_format() {
        let mut session = ClarificationSession::new("test");

        session.add_question(ClarificationQuestion {
            id: "features".to_string(),
            question_text: "Select features".to_string(),
            question_type: QuestionType::MultiSelect,
            options: Some(vec!["A".to_string(), "B".to_string(), "C".to_string()]),
            default_value: None,
            required: true,
            multi_select: true,
        });

        // Multi-select answers stored as comma-separated string
        session.answer_question("features", "A, C").unwrap();

        assert_eq!(session.answers.get("features"), Some(&"A, C".to_string()));
    }
}
